# Generated by Django 3.0.5 on 2020-06-01 10:17

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='deadline',
            field=models.DateTimeField(default=datetime.datetime(2020, 6, 2, 10, 17, 13, 320585, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
