# Generated by Django 3.0.5 on 2020-06-02 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_deadline'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tag',
            field=models.CharField(default='UnTagged', max_length=12),
        ),
    ]
