# Generated by Django 3.0.5 on 2020-06-05 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20200603_1723'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('Done', 'Done'), ('Not Done', 'Not Done')], default='Not Done', max_length=10),
        ),
    ]
